/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const CARD_HEIGHT = 168;  // height of a single card(excluding marginBottom/paddingBottom)
export const CARD_MARGIN = 32;  // height of a marginBottom+paddingBottom
export const OFFSET_HEIGHT = 84; // height offset from the top of the page

export const CLEAR_MAILBOX = 'CLEAR_MAILBOX';
export const SYNC_MAILBOX_PROFILE = 'SYNC_MAILBOX_PROFILE';
export const SYNC_MAILBOX_PROFILE_SUCCESS = 'SYNC_MAILBOX_PROFILE_SUCCESS';
export const SYNC_MAILBOX_PROFILE_FAILURE = 'SYNC_MAILBOX_PROFILE_FAILURE';

export const SET_GOOGLE_LABEL_INFO = 'SET_GOOGLE_LABEL_INFO';
export const SET_GOOGLE_LATEST_UNREAD_THREADS = 'SET_GOOGLE_LATEST_UNREAD_THREADS';
export const SET_GOOGLE_AUTH = 'SET_GOOGLE_AUTH';
export const SET_MAILBOX = 'SET_MAILBOX';

export const SYNC_MAILBOX_LABEL_START = 'SYNC_MAILBOX_LABEL_START';
export const SYNC_MAILBOX_LABEL_SUCCESS = 'SYNC_MAILBOX_LABEL_SUCCESS';
export const SYNC_MAILBOX_LABEL_FAILURE = 'SYNC_MAILBOX_LABEL_FAILURE';

export const GET_MAILBOX_LABEL_INFO_START = 'GET_MAILBOX_LABEL_INFO_START';
export const GET_MAILBOX_LABEL_INFO_SUCCESS = 'GET_MAILBOX_LABEL_INFO_SUCCESS';
export const GET_MAILBOX_LABEL_INFO_FAILURE = 'GET_MAILBOX_LABEL_INFO_FAILURE';


export const MOVE_CARD = 'MOVE_CARD';
